; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ./MaxDuino

[common]
lib_deps = 
	greiman/SdFat@2.2.3
	https://github.com/felias-fogg/SoftI2CMaster.git#5e7ac22
extra_scripts = 
	pre:extra_script.py
build_flags =
	-Wl,--relax
	-fmerge-all-constants
	-fno-threadsafe-statics
	-fno-use-cxa-atexit
	-fno-rtti
	-fno-exceptions
	-Os
avr_build_flags =
	${common.build_flags}
	-fshort-enums  # not safe for {common.build_flags} as causes isr failure on ESP32C3
	-flto
	-mcall-prologues
samd21_build_flags =
	${common.build_flags}
build_unflags =
	-fno-lto

[base]
framework = arduino
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags = ${common.build_flags}
build_unflags = ${common.build_unflags}

[base_nano_avr]
extends = base
board = nanoatmega328
board_upload.maximum_ram_size = 1835
platform = atmelavr
build_flags =
	${common.avr_build_flags}
	-DENABLE_DEDICATED_SPI=0
	-DUSE_FAT_FILE_FLAG_CONTIGUOUS=0
	-DCHECK_FLASH_PROGRAMMING=0

[env:seeed_xiao]
extends = base
platform = atmelsam
board = seeed_xiao
lib_ignore = USBHost
lib_archive = no
build_flags = 
	${common.samd21_build_flags}
	-DUSE_TINYUSB
	-I "${PROJECT_CORE_DIR}/packages/framework-arduino-samd-seeed/libraries/Adafruit_TinyUSB_Arduino/src/arduino"
	-DI2C_Library_Preference=_I2C_Impl_Wire ; silences warning about unsupported SoftI2CMaster

[env:seeed_xiao_ricky_test_board]
extends = base
platform = atmelsam
board = seeed_xiao
lib_ignore = USBHost
lib_archive = no
build_flags = 
	-DRICKY_TEST_BOARD
	${common.samd21_build_flags}
	-DUSE_TINYUSB
	-I "${PROJECT_CORE_DIR}/packages/framework-arduino-samd-seeed/libraries/Adafruit_TinyUSB_Arduino/src/arduino"
	-DI2C_Library_Preference=_I2C_Impl_Wire ; silences warning about unsupported SoftI2CMaster

[env:Nano328p]
extends = base_nano_avr
build_flags =
	${base_nano_avr.build_flags}
	-DCONFIGFILE=7

[env:Nano328p_LCD16]
extends = base_nano_avr
build_flags =
	${base_nano_avr.build_flags}
	-DCONFIGFILE=0

[env:Nano328p_CF0]
extends = base_nano_avr
build_flags =
	${base_nano_avr.build_flags}
	-DCONFIGFILE=0

[env:Nano328p_CF1]
extends = base_nano_avr
build_flags =
	${base_nano_avr.build_flags}
	-DCONFIGFILE=1

[env:Nano328p_CF2]
extends = base_nano_avr
build_flags =
	${base_nano_avr.build_flags}
	-DCONFIGFILE=2

[env:Nano328p_CF3]
extends = base_nano_avr
build_flags =
	${base_nano_avr.build_flags}
	-DCONFIGFILE=3

[env:Nano328p_CF4]
extends = base_nano_avr
build_flags =
	${base_nano_avr.build_flags}
	-DCONFIGFILE=4

[env:Nano328p_CF5]
extends = base_nano_avr
build_flags =
	${base_nano_avr.build_flags}
	-DCONFIGFILE=5

[env:Nano328p_CF6]
extends = base_nano_avr
build_flags =
	${base_nano_avr.build_flags}
	-DCONFIGFILE=6

[env:Nano328p_CF7]
extends = base_nano_avr
build_flags =
	${base_nano_avr.build_flags}
	-DCONFIGFILE=7
	-DLOGO=Maxduino7
	-DFONT=cartoonFont

[env:Nano328p_New]
extends = base_nano_avr
board = nanoatmega328new
build_flags =
	${base_nano_avr.build_flags}
	-DCONFIGFILE=7

[env:megaatmega2560_MegaDuino]
extends = base
platform = atmelavr
board = megaatmega2560
build_flags =
	${common.avr_build_flags}

[env:ATMEGA32u4_Miniduino]
extends = base_nano_avr
board = leonardo
build_flags =
	${base_nano_avr.build_flags}

[env:ThinaryNanoEvery_MaxduinoUltimate]
extends = base
platform = atmelmegaavr
board = ATmega4808
board_build.f_cpu = 16000000L
board_hardware.oscillator = internal
board_build.variant = nano-4808

[env:NanoEvery_MaxduinoUltimate]
extends = base
platform = atmelmegaavr
board = ATmega4809
board_build.f_cpu = 16000000L
board_hardware.oscillator = internal
board_build.variant = nano-every

[env:wemos_d1_mini8266]
extends = base
platform = espressif8266
board = d1_mini
lib_deps = ${common.lib_deps}
	jwrw/ESP_EEPROM@^2.2.1

[env:ESP32C3]
extends = base
platform = espressif32
board = seeed_xiao_esp32c3

[env:STM32_MapleMiniDuino]
extends = base
platform = ststm32
board = maple_mini_origin
board_build.core = maple
board_build.f_cpu = 72000000L
  
; Lotharek device untested and has reported issues, so we need a donor to confirm build configuration
[env:STM32_MaxDuino_Mini_Lotharek_maple_build]
extends = base
platform = ststm32
board = genericSTM32F103C8
board_build.core = maple
board_build.mcu = stm32f103c8t6
board_build.f_cpu = 72000000L

[env:RaspberryPiPico]
extends = base
platform = https://github.com/maxgerhardt/platform-raspberrypi.git  ; official PlatformIO raspberrypi platform has been abandoned, this community fork is highly regarded and maintained
board = pico
board_build.core = earlephilhower
board_build.filesystem_size = 0m ; not using LittleFS (.. yet?)
build_flags =
	-DI2C_Library_Preference=_I2C_Impl_Wire ; silences warning about unsupported SoftI2CMaster

[env:wemos_d1_mini32]
extends = base
platform = espressif32
board = wemos_d1_mini32
build_flags =
	-DWEMOS_D1_MINI32=1 ; just used to identify the board (i.e. pin layout)
	-DI2C_Library_Preference=_I2C_Impl_Wire ; silences warning about unsupported SoftI2CMaster
