; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ./MaxDuino

[common]
lib_deps = 
	greiman/SdFat@^2.2.3
	https://github.com/felias-fogg/SoftI2CMaster.git#5e7ac22
extra_scripts = 
	pre:extra_script.py

[env:seeed_xiao]
platform = atmelsam
board = seeed_xiao
framework = arduino
lib_ignore = USBHost
lib_deps = ${common.lib_deps}
build_flags = 
	-DUSE_TINYUSB
	-I "${PROJECT_CORE_DIR}/packages/framework-arduino-samd-seeed/libraries/Adafruit_TinyUSB_Arduino/src/arduino"
extra_scripts = ${common.extra_scripts}

[env:Nano328p]
framework = arduino
platform = atmelavr
board = nanoatmega328
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	-DCONFIGFILE=7
	-flto
	-mcall-prologues
	-fshort-enums
	-fno-threadsafe-statics
	-fno-use-cxa-atexit
	-fno-rtti
	-fno-exceptions
	-DENABLE_DEDICATED_SPI=0
	-DUSE_FAT_FILE_FLAG_CONTIGUOUS=0
	-DCHECK_FLASH_PROGRAMMING=0
	-DENABLE_DEDICATED_SPI=0
	-DUSE_FAT_FILE_FLAG_CONTIGUOUS=0
	-DCHECK_FLASH_PROGRAMMING=0
build_unflags =
	-fno-lto

[env:Nano328p_LCD16]
framework = arduino
platform = atmelavr
board = nanoatmega328
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	-DCONFIGFILE=0

[env:Nano328p_CF0]
framework = arduino
platform = atmelavr
board = nanoatmega328
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	-DCONFIGFILE=0

[env:Nano328p_CF1]
framework = arduino
platform = atmelavr
board = nanoatmega328
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	-DCONFIGFILE=1

[env:Nano328p_CF2]
framework = arduino
platform = atmelavr
board = nanoatmega328
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	-DCONFIGFILE=2

[env:Nano328p_CF3]
framework = arduino
platform = atmelavr
board = nanoatmega328
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	-DCONFIGFILE=3

[env:Nano328p_CF4]
framework = arduino
platform = atmelavr
board = nanoatmega328
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	-DCONFIGFILE=4

[env:Nano328p_CF5]
framework = arduino
platform = atmelavr
board = nanoatmega328
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	-DCONFIGFILE=5

[env:Nano328p_CF6]
framework = arduino
platform = atmelavr
board = nanoatmega328
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	-DCONFIGFILE=6

[env:Nano328p_CF7]
framework = arduino
platform = atmelavr
board = nanoatmega328
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	${env:Nano328p.build_flags}
	-DCONFIGFILE=7
	-DLOGO=Maxduino7
	-DFONT=cartoonFont
build_unflags =
	${env:Nano328p.build_unflags}

[env:Nano328p_CF8]
framework = arduino
platform = atmelavr
board = nanoatmega328
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	-DCONFIGFILE=8

[env:Nano328p_CF9]
framework = arduino
platform = atmelavr
board = nanoatmega328
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	-DCONFIGFILE=9

;commenting out for now, since PCD8544 isn't functional
;[env:Nano328p_CF10]
;framework = arduino
;platform = atmelavr
;board = nanoatmega328
;lib_deps = ${common.lib_deps}
;extra_scripts = ${common.extra_scripts}
;build_flags =
;	-DCONFIGFILE=10
;	-DLOGO=LOGOARDUITAPE

[env:Nano328p_New]
framework = arduino
platform = atmelavr
board = nanoatmega328new
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	-DCONFIGFILE=7

[env:megaatmega2560_MegaDuino]
framework = arduino
platform = atmelavr
board = megaatmega2560
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}

[env:ThinaryNanoEvery_MaxduinoUltimate]
framework = arduino
platform = atmelmegaavr
board = ATmega4808
board_build.f_cpu = 16000000L
board_hardware.oscillator = internal
board_build.variant = nano-4808
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	-DPIO_EVERY_BUILD=1
	-flto
	-mcall-prologues
	-Wl,--relax
	-fshort-enums
	-fmerge-all-constants
	-fno-threadsafe-statics
	-fno-use-cxa-atexit
	-fno-rtti
	-fno-exceptions
	-DENABLE_DEDICATED_SPI=0
	-DUSE_FAT_FILE_FLAG_CONTIGUOUS=0
	-DCHECK_FLASH_PROGRAMMING=0
build_unflags =
	-fno-lto

[env:NanoEvery_MaxduinoUltimate]
framework = arduino
platform = atmelmegaavr
board = ATmega4809
board_build.f_cpu = 16000000L
board_hardware.oscillator = internal
board_build.variant = nano-every
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	-DPIO_EVERY_BUILD=1
	-flto
	-mcall-prologues
	-Wl,--relax
	-fshort-enums
	-fmerge-all-constants
	-fno-threadsafe-statics
	-fno-use-cxa-atexit
	-fno-rtti
	-fno-exceptions
	-DENABLE_DEDICATED_SPI=0
	-DUSE_FAT_FILE_FLAG_CONTIGUOUS=0
	-DCHECK_FLASH_PROGRAMMING=0
build_unflags =
	-fno-lto

[env:ArduinoNanoEvery]
framework = arduino
platform = atmelmegaavr
board = ATmega4809
board_build.mcu = atmega4809
board_build.f_cpu = 16000000L
board_hardware.oscillator = internal
board_build.variant = nano-every
upload_protocol = jtag2updi
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
board_upload.use_1200bps_touch = yes
board_upload.wait_for_upload_port = yes
build_flags =
	-DPIO_EVERY_BUILD=1
	-flto
	-mcall-prologues
	-Wl,--relax
	-fshort-enums
	-fmerge-all-constants
	-fno-threadsafe-statics
	-fno-use-cxa-atexit
	-fno-rtti
	-fno-exceptions
	-DENABLE_DEDICATED_SPI=0
	-DUSE_FAT_FILE_FLAG_CONTIGUOUS=0
	-DCHECK_FLASH_PROGRAMMING=0
build_unflags =
	-fno-lto
[env:wemos_d1_mini8266]
framework = arduino
platform = espressif8266
board = d1_mini
lib_deps = ${common.lib_deps}
	jwrw/ESP_EEPROM@^2.2.1
extra_scripts = ${common.extra_scripts}

[env:ESP32C3]
framework = arduino
platform = espressif32
board = seeed_xiao_esp32c3
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}

[env:wemos_d1_mini32]
framework = arduino
platform = espressif32
board = wemos_d1_mini32
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}

[env:RaspberryPiPico]
framework = arduino
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
board_build.core = earlephilhower
board_build.filesystem_size = 0m
lib_deps = ${common.lib_deps}
extra_scripts = ${common.extra_scripts}
build_flags =
	-DMAXDUINO_RP2040
	-DI2C_Library_Preference=_I2C_Impl_Wire
;[env:STM32_MapleMiniDuino]
;framework = arduino
;platform = ststm32
;board = maple_mini_origin
;board_build.core = maple
;lib_deps = ${common.lib_deps}
;extra_scripts = ${common.extra_scripts}

;[env:STM32_MapleMiniDuino_CF0]
;framework = arduino
;platform = ststm32
;board = maple_mini_origin
;board_build.core = maple
;lib_deps = ${common.lib_deps}
;extra_scripts = ${common.extra_scripts}
;build_flags =
;	-DCONFIGFILE=0


